### ISSUE TITLE
workflow progress

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-workflow-controller#89]
copying from the discussion on gitter:

my proposal

```yaml
jobs:
- jobid: 'job-1'
  status: SUCCESS
  command: root -f ...
  created: '2018/06/14 08:01'
- jobid: 'job-2'
  status: RUNNING
  command: root -f ...
  created: '2018/06/14 08:01'
wflow:
  status: RUNNING
  structure:
    sequence:
    - name: generate
      jobid: 'job-1'
    - name: fit
      jobid: 'job-2'
    - name: fit
      jobid: null # (not submitted yet, so o no associated job id)
  progress:
    planned: 3
    submitted: 2
    succeeded: 1
    failed: 0
  logs:
  - {type: console_log, msg: 'hello world 1'} 
  - {type: console_log, msg: 'hello world 2'} 
  - {type: console_log, msg: 'hello world 3'}
```

pars:

* job information to be filled from the job controller / tables

I removed the logs field. one issue with the logs is that they may become large.. perhaps it's better to have that be a seaprate HTTP request from a given frontend given the jobid or have the client request this to be inlined explicitly

* wflow information will be filled by the engine

progress: I see this as engine-agnostic progress. we need to think what this could be, but right now it seems like summarizing
* the number of currently expected steps to be run
* the number of submitted steps (those that have a job-id)
* the number of succeeded steps
* the number of failed steps 

seems to be agnostic enought.. if even this is not common, perhaps in the future this entire section is removed

structure:

this section describes the engine-specific workflow structure which builds semantic relations between stages of the workflow and jobs/job-ids.. in the case of the serial engine it might just be a map of `"step1"->job-1234`, `"step1"->job-9876`, `"step3"->null` . for other engines such as yadage the structure might be more complicated

cc'ing for comment: 

@tiborsimko @diegodelemos @dinosk
